#
# はじめに以下を実行する
# xcode-select --install
# ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# brew install rbenv
# brew install ruby-build
# brew install rbenv-gemset
# brew install readline
# 
# brew install zsh
# curl -L http://install.ohmyz.sh | sh
# cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
# chsh -s /bin/zsh
#
# brew tap homebrew/boneyard
#
# 
# defaults write com.apple.finder AppleShowAllFiles -boolean true
# killall Finder
# 
# HOMEBREW_CASK_OPTS="--appdir=/Applications" brew bundle
#
# cp -f /usr/local/Cellar/ricty/3.2.4/share/fonts/*.ttf ~/Library/Fonts/ 
# fc-cache -vf
#
# http://nanapi.co.jp/blog/2014/03/05/homebrew-cask/
# http://nwpct1.hatenablog.com/entry/2014/03/21/001609
# http://mizchi.hatenablog.com/entry/2014/03/02/090517
# http://blog.livedoor.jp/xaicron/archives/54458405.html
#


# update
update
upgrade


# tap
tap sanemat/font 


# cask
install caskroom/cask/brew-cask

# reupdate
update
upgrade


# install
install rbenv ruby-build zsh git sl ctags mysql tmux openssl cmake fish wget curl libtool automake tig ag z mongodb readline hub gist llvm go erlang scala sbt nginx memcached redis sqlite dnsmasq python nmap htop-osx reattach-to-user-namespace colordiff pstree ngrep httping

install vim
install imagemagick
install wget
install heroku-toolbelt
install rmtrash
install tree
install ansible

install --default-names gnu-tar

brew install ghc cabal-install


# cask install
cask install java
cask install xquartz
cask install sublime-text 
cask install iterm2
cask install google-chrome
cask install virtualbox
cask install vagrant
cask install kobito
cask install caffeine
cask install dropbox
cask install evernote
cask install skitch
cask install sequel-pro
cask install sourcetree
cask install 1password
cask install dash
cask install firefox
cask install slack
cask install skype
cask install sqwiggle
cask install arduino
cask install clipmenu
cask install google-drive
cask install google-hangouts
cask install google-japanese-ime
cask install android-studio
cask install adobe-reader
cask install appcleaner
cask install hyperswitch
cask install flux
cask install clamxav
cask install charles
cask install the-unarchiver
cask install opera
cask install libreoffice
cask install robomongo
cask install vlc
cask install unity
cask install teamviewer

install elasticsearch

install --powerline --vim-powerline ricty

cask install alfred

#alfredにsymlinkのアプリを認識させる
#syncedfolderがないって怒られるがpowerpackが必要のようなので
#http://qiita.com/kiyodori/items/11a314dcea71b2929d17
#を実行してalfredの検索範囲にcaskがAppをインストールするディレクトリを追加
#cask alfred link


#手動インストール
#line
#airmail
#moon
#kiritori
#freememory
#simplenote
#onix
#canary
#3hub
#Firefox Developer Edition
#keyremap4
#sublime text3

# 不要なファイルを削除
cleanup

